# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('cparent', models.CharField(max_length=30)),
                ('cis_featured', models.CharField(max_length=30)),
                ('cimage', models.CharField(max_length=30)),
                ('cis_active', models.CharField(max_length=30)),
                ('cdescription', models.CharField(max_length=30)),
                ('ccreated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpublished_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
